"""
Dashboard Review Details.
"""

import streamlit as st

from models.review_model import ReviewResult

from components.ui.section_header import (
    render_section_header,
)

from components.ui.document_preview import (
    render_document_preview,
)

from components.ui.status_badge import (
    render_status_badge,
)


def render_review_details(
    review: ReviewResult,
):
    """
    Render the complete AI review.
    """

    render_section_header(
        "🤖 AI Resume Review",
        "Detailed feedback generated by HireMate AI.",
    )

    render_document_preview(
        "📄 Overall Summary",
        review.summary,
    )

    st.subheader("✅ Strengths")

    if review.strengths:

        for item in review.strengths:

            render_status_badge(
                "success",
                item,
            )

    else:

        render_status_badge(
            "info",
            "No strengths identified.",
        )

    st.divider()

    st.subheader("⚠ Weaknesses")

    if review.weaknesses:

        for item in review.weaknesses:

            render_status_badge(
                "warning",
                item,
            )

    else:

        render_status_badge(
            "success",
            "No weaknesses identified.",
        )

    st.divider()

    st.subheader("💡 Recommendations")

    if review.recommendations:

        for item in review.recommendations:

            render_status_badge(
                "info",
                item,
            )

    else:

        render_status_badge(
            "success",
            "No recommendations available.",
        )