"""
Dashboard Review Overview.
"""

from models.review_model import ReviewResult

from components.ui.document_preview import (
    render_document_preview,
)

from components.ui.section_header import (
    render_section_header,
)


def render_review_overview(
    review: ReviewResult,
):
    """
    Render AI review summary.
    """

    render_section_header(
        "🤖 AI Review",
        "Quick summary generated by HireMate AI.",
    )

    render_document_preview(
        "Review Summary",
        review.summary,
    )