"""
Dashboard Summary Card.
"""

import streamlit as st

from components.ui.section_header import (
    render_section_header,
)


def render_summary_card(
    summary: str,
):
    """
    Render AI resume summary.
    """

    render_section_header(
        "🤖 AI Resume Summary",
        "A concise overview generated by HireMate AI.",
    )

    st.info(summary)