"""
Recommendation Dashboard Tab.

Responsibilities:
- Display AI-generated career recommendations
"""

import streamlit as st

from models.recommendation_model import RecommendationResult

from components.cards.recommendation_card import (
    render_recommendation_card,
)


# ==========================================================
# Recommendation Tab
# ==========================================================


def render_recommendation_tab(
    recommendations: RecommendationResult,
):
    """
    Render the AI Career Recommendations dashboard tab.
    """

    render_recommendation_card(
        recommendations,
    )

    st.divider()

    total = (
        len(recommendations.ats_optimization)
        + len(recommendations.skills_to_learn)
        + len(recommendations.resume_improvements)
        + len(recommendations.next_steps)
    )

    if total > 0:

        st.success(
            f"{total} personalized recommendation(s) generated."
        )

    else:

        st.info(
            "No recommendations available."
        )

    st.caption(
        "Recommendations are generated by analyzing your resume "
        "against the uploaded job description using AI."
    )